#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Feb  4 17:19:20 2020

@author: panda
"""


import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

print("hola mundo")


#importar el dataset
dataset = pd.read_csv("Data.csv")
x = dataset.iloc[:, : -1].values
y = dataset.iloc[:, 3].values


#Codificar categorias nombres
from sklearn.preprocessing import  OneHotEncoder, LabelEncoder
from sklearn.compose import make_column_transformer

onehotencoder = make_column_transformer((OneHotEncoder(), [0]), remainder = "passthrough")
x = onehotencoder.fit_transform(x)

#codificar caterias purchased
labelencoder_y = LabelEncoder()
y = labelencoder_y.fit_transform(y)