#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Feb  4 17:19:20 2020

@author: panda
"""


import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

print("hola mundo")


#importar el dataset
dataset = pd.read_csv("Data.csv")
x = dataset.iloc[:, : -1].values
y = dataset.iloc[:, 3].values



#tratamiento de los N
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(strategy='mean')
imputer = imputer.fit(x[:,1:3])
x[:, 1:3]=imputer.transform(x[:, 1:3])