#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Feb  4 17:19:17 2020
@author: panda
"""
# -*- coding: utf-8 -*-
"""
Spyder Editor

This is a temporary script file.
"""
#platilla de procesado
#como improtar
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


#importar el dataset
dataset = pd.read_csv("Data.csv")
x = dataset.iloc[:, : -1].values
y = dataset.iloc[:, 3].values



#dividir dataset en entrenamiento y prueba
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.2, random_state = 0)


#escalado de variables
from sklearn.preprocessing import StandardScaler
sc_x = StandardScaler()
x_train = sc_x.fit_transform(x_train)
x_test = sc_x.fit_transform(x_test)



