#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Feb  5 17:15:41 2020

@author: panda
"""
#como improtar
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


#importar el dataset
dataset = pd.read_csv("50_Startups.csv")

x = dataset.iloc[:, : -1].values
y = dataset.iloc[:, -1].values



#Codificar categorias nombres
from sklearn.preprocessing import  OneHotEncoder, LabelEncoder
from sklearn.compose import make_column_transformer
onehotencoder = make_column_transformer((OneHotEncoder(), [3]), remainder = "passthrough")
x = onehotencoder.fit_transform(x)

#evitar la trampa de las variables dummy
x = x[:,1:]




#dividir dataset en entrenamiento y prueba
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.2, random_state = 0)

#escalado de variables
"""from sklearn.preprocessing import StandardScaler
sc_x = StandardScaler()
x_train = sc_x.fit_transform(x_train)
x_test = sc_x.fit_transform(x_test)"""

#ajustar el modelo de regresion lineal con el conjunto de entrenamiento

from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(x_train,y_train)


#predicción de los resultados del conjunto testing

y_pred = regressor.predict(x_test)




















